version: '3.3'
services:
  nginx-proxy:
    ports:
      - '80:80'
      - '443:443'
    container_name: nginx-proxy
    volumes:
      - '$HOME/certs:/etc/nginx/certs:ro'
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true
    image: jwilder/nginx-proxy

  letsencrypt-nginx-proxy-companion:
    container_name: nginx-letsencrypt
    volumes:
      - '$HOME/certs:/etc/nginx/certs:rw'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    image: jrcs/letsencrypt-nginx-proxy-companion

  bonavoy-api:
    container_name: bonavoy-api
    environment:
      - LETSENCRYPT_EMAIL=bonavoydevelopers@gmail.com
      - LETSENCRYPT_HOST=api.bonavoy.com
      - VIRTUAL_HOST=api.bonavoy.com
    image: bonavoy-api:latest
